namespace Client
{
    public class PedAnimations
    {
        public static dynamic[,] Actions =
        {
            {"Поднять руки", "random@mugging3", "handsup_standing_base", 49 },
            {"Передать что-то по рации", "random@arrests", "generic_radio_chatter", 49 },
            {"Рука на кобуре", "move_m@intimidation@cop@unarmed","idle", 49 },
            {"Свистнуть", "taxi_hail", "fp_hail_taxi", 8 },
            {"Выполнить воиское приветствие", "anim@mp_player_intincarsalutestd@ds@", "idle_a", 8 },
            {"Показать пальцем", "gestures@m@standing@casual", "gesture_point", 8 },
            {"Согласиться-1", "gestures@m@standing@casual", "gesture_i_will", 8 },
            {"Согласиться-2", "gestures@m@standing@fat", "gesture_bye_soft", 8 },
            {"Отказать-1", "gestures@m@standing@casual", "gesture_nod_no_hard", 8 },
            {"Отказать-2", "gestures@m@standing@casual", "gesture_no_way", 8 },
            {"Отказать-3", "amb@code_human_in_car_mp_actions@nod@bodhi@ds@base", "nod_no_fp", 8 },
            {"Пожать плечами", "gestures@m@standing@casual", "gesture_what_soft", 8 },
            {"Положить что-то в рот", "mp_player_int_uppersmoke", "mp_player_int_smoke_enter", 8 },
            {"Закинуться", "move_m@drunk@transitions", "slightly_to_idle", 8 },
            {"Постучать", "amb@code_human_in_car_mp_actions@dance@bodhi@ps@base", "idle_a_fp", 8 },
            {"Ударить по лежащему", "anim@heists@ornate_bank@hostages@hit", "player_melee_long_pistol_a", 8 },
            {"Пнуть ногой", "anim@mp_freemode_return@f@fail", "fail_a", 8 },
            {"Махать руками", "random@car_thief@victimpoints_ig_3", "arms_waving", 8 },
            {"Отмахнуться-1", "taxi_hail", "forget_it", 8 },
            {"Отмахнуться-2", "anim@mp_freemode_return@f@idle", "idle_b", 8 },
            {"Подобрать с земли", "random@mugging4", "pickup_low", 8 },
            {"Осмотреть землю", "amb@code_human_police_investigate@idle_b", "idle_f", 8 },
            {"Ковырять в земле", "amb@world_human_bum_wash@male@high@idle_a", "idle_a", 8 },
            {"Схватиться за живот", "rcmpaparazzo1", "idle", 8 },
            {"Почесать задницу", "anim@heists@team_respawn@respawn_02", "heist_spawn_02_ped_d", 8 },
            {"Помолиться", "pro_mcs_7_concat-0", "cs_priest_dual-0", 8 },
            {"Поклониться-1", "anim@mp_player_intcelebrationpaired@f_f_sarcastic", "sarcastic_right", 8 },
            {"Поклониться-2", "anim@mp_player_intcelebrationpaired@m_m_sarcastic", "sarcastic_left", 8 },
            {"Отжаться", "amb@world_human_push_ups@male@base", "base", 8 },
            {"Качать пресс", "amb@world_human_sit_ups@male@base", "base", 8 },
            {"Отдышаться", "timetable@reunited@ig_2", "jimmy_base", 8 },
            {"Потерять сознание", "missfam5_blackout", "pass_out", 8 },
            {"Умыться", "missfam2_washing_face", "michael_washing_face", 8 },
            {"Потереть шею", "amb@world_human_cop_idles@female@idle_a", "idle_c", 8 },
            {"Потереть ладони", "amb@world_human_cop_idles@female@idle_b", "idle_d", 8 },
            {"Потереть руки", "move_action@p_m_one@unarmed@idle@variations", "idle_a", 8 },
            {"Показать два пальца", "amb@code_human_in_car_mp_actions@v_sign@bodhi@rps@base", "idle_a", 8 },
            {"Смотреть по сторонам", "amb@world_human_guard_patrol@male@idle_a", "idle_b", 8 },
            {"Осмотреть", "amb@medic@standing@kneel@enter", "enter", 8 },
            {"Высматривать", "missmic4premiere", "crowd_c_idle_01", 8 },
            {"Тссс", "anim@mp_player_intcelebrationfemale@shush", "shush", 8 },
            {"Ковырять в носу", "anim@mp_player_intcelebrationfemale@nose_pick", "nose_pick", 8 },
            {"Подумать", "amb@code_human_police_investigate@idle_a", "idle_a", 8 },
            {"Собирать в руках", "amb@prop_human_movie_studio_light@idle_a", "idle_a", 8 },
            {"Греться у костра", "amb@world_human_stand_fire@male@base", "base", 9 },
            {"Принимать душ", "mp_safehouseshower@male@", "male_shower_idle_d", 8 },
			
            {"Секс (Мужчина)", "rcmpaparazzo_2", "shag_action_a", 8 },
            {"Секс (Женщина)", "rcmpaparazzo_2", "shag_action_poppy", 8 },
        };
        
        public static dynamic[,] Pose =
        {
            {"Руки вверх", "anim@move_hostages@male", "male_idle", 9 },
            {"Руки за голову", "anim@heists@ornate_bank@hostages@cashier_b@", "flinch_loop_underfire", 8 },
            {"Руки за спину", "anim@miss@low@fin@vagos@", "idle_ped06", 8 },
            {"Просить пощады", "amb@code_human_cower@male@react_cowering", "base_front", 9 },
            {"Присесть-1", "anim@miss@low@fin@lamar@", "idle", 9 },
            {"Присесть-2", "amb@medic@standing@tendtodead@enter", "enter", 8 },
            {"Присесть-3", "amb@medic@standing@kneel@base", "base", 9 },
            /*{"Сидеть-1", "amb@prop_human_seat_chair@male@generic@base", "base", 9 },
            {"Сидеть-2", "amb@prop_human_seat_chair@male@elbows_on_knees@base", "base", 9 },
            {"Сидеть-3", "amb@prop_human_seat_chair@male@left_elbow_on_knee@base", "base", 9 },
            {"Сидеть-4", "amb@prop_human_seat_chair@male@right_foot_out@base", "base", 9 },*/
            {"Лечь на бок", "amb@world_human_bum_slumped@male@laying_on_right_side@base", "base", 9 },
            {"Лечь на живот", "amb@world_human_sunbathe@male@front@base", "base", 9 },
            {"Лечь на спину", "missfbi1", "cpr_pumpchest_idle", 9 },
            {"Распальцовка-1", "missmic4premiere", "wave_b", 8 },
            {"Распальцовка-2", "amb@code_human_in_car_mp_actions@v_sign@std@rds@base", "enter", 8 },
            {"Пальцы вверх", "anim@mp_player_intcelebrationfemale@thumbs_up", "thumbs_up", 8 },
            {"Палец вверх", "anim@mp_player_intincarthumbs_upbodhi@ds@", "enter_fp", 8 },
            {"Скрестить руки-1", "rcmme_amanda1", "stand_loop_cop", 9 },
            {"Скрестить руки-2", "amb@world_human_cop_idles@female@idle_b", "idle_e", 8 },
            {"Руки в боки", "amb@code_human_police_investigate@base", "base", 9 },
            {"Поза охранника", "missfbi4mcs_2", "loop_sec_b", 9 },
            {"Бег на месте разводя руки", "amb@world_human_jog_standing@female@idle_a", "idle_a", 8 },
            {"Бег на месте", "amb@world_human_jog_standing@male@base", "base", 8 },
            {"Размяться-1", "amb@world_human_muscle_flex@arms_at_side@idle_a", "idle_a", 8 },
            {"Размяться-2", "timetable@tracy@ig_5@idle_b", "idle_d", 8 },
            {"Показать бицепс-1", "amb@world_human_muscle_flex@arms_at_side@idle_a", "idle_c", 8 },
            {"Показать бицепс-2", "amb@world_human_muscle_flex@arms_in_front@base", "base", 8 },
            {"Расставить руки в стороны", "missfam5_yoga", "c1_pose", 8 },
            {"Расставить руки и ноги в стороны", "missfam5_yoga", "a2_pose", 8 },
            {"Медитировать-1", "missfam5_yoga", "f_yogapose_a", 8 },
            {"Медитировать-2", "missfam5_yoga", "c8_pose", 8 },
            {"Медитировать-3", "missfam5_yoga", "b4_fail_to_start", 8 },
            {"Медитировать-4", "missfam5_yoga", "start_to_c1", 8 },
            {"Медитировать-5", "missfam5_yoga", "start_to_a1", 8 },
            {"Медитировать-6", "missfam5_yoga", "a2_to_a3", 8 },
            {"Медитировать-7", "missfam5_yoga", "a3_fail_to_start", 8 },
        };
        
        public static dynamic[,] Positive =
        {
            {"Радоваться-1", "missmic_4premiere", "movie_prem_01_f_a", 8 },
            {"Радоваться-2", "mini@dartsoutro", "darts_outro_03_guy2", 8 },
            {"Радоваться-3", "mini@dartsoutro", "darts_outro_01_guy1", 8 },
            {"Радоваться-4", "anim@mp_player_intcelebrationfemale@freakout", "freakout", 8 },
            {"Хлопать в ладоши-1", "missmic_4premiere", "movie_prem_02_f_a", 8 },
            {"Хлопать в ладоши-2", "amb@world_human_cheering@female_d", "base", 8 },
            {"Хлопать в ладоши-3", "amb@world_human_cheering@male_a", "base", 8 },
            {"Хлопать в ладоши-4", "amb@world_human_cheering@male_e", "base", 8 },
            {"Хлопать в ладоши-5", "anim@mp_player_intcelebrationfemale@slow_clap", "slow_clap", 8 },
            {"Поддержать-1", "amb@world_human_cheering@female_a", "base", 8 },
            {"Поддержать-2", "amb@world_human_cheering@female_c", "base", 8 },
            {"Поддержать-3", "amb@world_human_cheering@male_b", "base", 8 },
            {"Поцеловать-1", "anim@mp_player_intcelebrationfemale@blow_kiss", "blow_kiss", 8 },
            {"Поцеловать-2", "anim@mp_player_intcelebrationfemale@chin_brush", "chin_brush", 8 },
            {"Поцеловать-3", "anim@mp_player_intcelebrationfemale@finger_kiss", "finger_kiss", 8 },
            {"Успокоить", "amb@code_human_police_crowd_control@idle_a", "idle_c", 8 },
            {"Уважение", "anim@mp_player_intcelebrationfemale@bro_love", "bro_love", 8 },
        };
        
        public static dynamic[,] Negative =
        {
            {"Размять кулаки-1", "anim@mp_player_intcelebrationfemale@knuckle_crunch", "knuckle_crunch", 8 },
            {"Размять кулаки-2", "anim@mp_player_intincarknuckle_crunchbodhi@ps@", "idle_a_fp", 8 },
            {"Разочароваться", "mini@dartsoutro", "darts_outro_03_guy1", 8 },
            {"Виноват", "anim@mp_parachute_outro@female@lose", "lose_loop", 8 },
            {"Дурак", "anim@mp_player_intcelebrationfemale@you_loco", "you_loco", 8 },
            {"Facepalm", "anim@mp_player_intcelebrationfemale@face_palm", "face_palm", 8 },
            {"Расстрелять", "amb@world_human_superhero@male@space_pistol@idle_a", "idle_b", 8 },
            {"С ружьем", "anim@deathmatch_intros@2hcombat_mgmale", "intro_male_mg_c", 8 },
            {"С битой", "anim@deathmatch_intros@melee@2h", "intro_male_melee_2h_b_gclub", 8 },
            {"Встать в стойку-1", "anim@deathmatch_intros@unarmed", "intro_male_unarmed_c", 8 },
            {"Встать в стойку-2", "anim@deathmatch_intros@unarmed", "intro_male_unarmed_a", 8 },
            {"Встать в стойку-3", "anim@deathmatch_intros@unarmed", "intro_male_unarmed_b", 8 },
            {"Встать в стойку-4", "anim@deathmatch_intros@unarmed", "intro_male_unarmed_d", 8 },
        };
        
        public static dynamic[,] Dance =
        {
            {"DJ", "anim@mp_player_intcelebrationfemale@dj", "dj", 8 },
            {"Танец-1", "misschinese2_crystalmazemcs1_ig", "dance_loop_tao", 9 },
            {"Танец-2", "mini@strip_club@lap_dance_2g@ld_2g_p2", "ld_2g_p2_s1", 9 },
            {"Танец-3", "mini@strip_club@lap_dance_2g@ld_2g_p3", "ld_2g_p3_s2", 9 },
            {"Танец-4", "amb@world_human_partying@female@partying_beer@idle_a", "idle_b", 9 },
            {"Танец-5", "amb@world_human_prostitute@cokehead@idle_a", "idle_a", 9 },
            {"Танец-6", "amb@world_human_prostitute@cokehead@idle_a", "idle_c", 9 },
            {"Танец-7", "amb@world_human_jog_standing@female@base", "base", 9 },
            {"Танец-8", "timetable@tracy@ig_8@idle_a", "idle_a", 8 },
            {"Танец-9", "timetable@tracy@ig_5@idle_a", "idle_a", 9 },
            {"Танец-10", "timetable@tracy@ig_5@idle_a", "idle_b", 9 },
            {"Танец-11", "timetable@tracy@ig_5@idle_a", "idle_c", 9 },
            {"Танец-12", "oddjobs@assassinate@multi@yachttarget@lapdance", "yacht_ld_f", 8 },
            {"Танец-13", "mp_safehouse", "lap_dance_girl", 8 },
            {"Танец 14", "amb@code_human_in_car_mp_actions@dance@bodhi@rds@base", "idle_b", 9},
            {"Танец 15", "amb@code_human_in_car_mp_actions@dance@std@ds@base", "idle_a", 9},
            {"Танец 16", "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_male^6", 9},
            {"Танец 17", "anim@amb@nightclub@dancers@crowddance_facedj@low_intesnsity", "li_dance_facedj_09_v1_male^6", 9},
            {"Танец 18", "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", "trans_dance_facedj_hi_to_li_09_v1_male^6", 9},
            {"Танец 19", "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_low_intensity", "trans_dance_facedj_li_to_hi_07_v1_male^6", 9},
            {"Танец 20", "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_13_v2_male^6", 9},
            {"Танец 21", "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", "trans_dance_crowd_hi_to_li__07_v1_male^6", 9},
            {"Танец 22", "anim@amb@nightclub@dancers@crowddance_single_props@hi_intensity", "hi_dance_prop_13_v1_male^6", 9},
            {"Танец 23", "anim@amb@nightclub@dancers@crowddance_single_props_transitions@from_med_intensity", "trans_crowd_prop_mi_to_li_11_v1_male^6", 9},
            {"Танец 24", "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", "med_center_up", 9},
            {"Танец 25", "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", "med_right_up", 9},
            {"Танец 26", "anim@amb@nightclub@dancers@crowddance_groups@low_intensity", "li_dance_crowd_17_v1_male^6", 9},
            {"Танец 27", "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_med_intensity", "trans_dance_facedj_mi_to_li_09_v1_male^6", 9},
            {"Танец 28", "timetable@tracy@ig_5@idle_b", "idle_e", 9},
            {"Танец 29", "mini@strip_club@idles@dj@idle_04", "idle_04", 9},
            {"Танец 30", "special_ped@mountain_dancer@monologue_1@monologue_1a", "mtn_dnc_if_you_want_to_get_to_heaven", 9},
            {"Танец 31", "special_ped@mountain_dancer@monologue_4@monologue_4a", "mnt_dnc_verse", 9},
            {"Танец 32", "special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag", 9},
            {"Танец 33", "anim@amb@nightclub@dancers@black_madonna_entourage@", "hi_dance_facedj_09_v2_male^5", 9},
            {"Танец 34", "anim@amb@nightclub@dancers@crowddance_single_props@", "hi_dance_prop_09_v1_male^6", 9},
            {"Танец 35", "anim@amb@nightclub@dancers@dixon_entourage@", "mi_dance_facedj_15_v1_male^4", 9},
            {"Танец 36", "anim@amb@nightclub@dancers@podium_dancers@", "hi_dance_facedj_17_v2_male^5", 9},
            {"Танец 37", "anim@amb@nightclub@dancers@tale_of_us_entourage@", "mi_dance_prop_13_v2_male^4", 9},
            {"Танец 38", "misschinese2_crystalmazemcs1_cs", "dance_loop_tao", 9},
            {"Танец 39", "anim@mp_player_intcelebrationfemale@uncle_disco", "uncle_disco", 9},
            {"Танец 40", "anim@mp_player_intcelebrationfemale@raise_the_roof", "raise_the_roof", 9},
            {"Танец 41", "anim@mp_player_intcelebrationmale@cats_cradle", "cats_cradle", 9}, 
            {"Танец 42", "anim@mp_player_intupperbanging_tunes", "idle_a", 9}, 
            {"Танец 43", "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center", 9}, 
            {"Танец 44", "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "high_center", 9}, 
            {"Танец 45", "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", "high_center", 9}, 
            {"Танец 46", "anim@amb@nightclub@dancers@crowddance_facedj_transitions@", "trans_dance_facedj_hi_to_mi_11_v1_female^6", 9},
            {"Танец 47", "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", "trans_dance_facedj_hi_to_li_07_v1_female^6", 9},
            {"Танец 48", "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_female^6", 9},
            {"Танец 49", "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_09_v1_female^6", 9}, 
            {"Танец 50", "anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_06_base_laz", 9}, 
            {"Танец 51", "special_ped@zombie@monologue_4@monologue_4l", "iamtheundead_11", 9},
			{"Танец 52", "anim@amb@nightclub@dancers@club_ambientpeds@med-hi_intensity", "mi-hi_amb_club_10_v1_male^6", 9},
            {"Пританцовывать", "misscarsteal4@toilet", "desperate_toilet_idle_a", 9 },
        };
        
        public static dynamic[,] Remain =
        {
            {"Секс-1", "anim@mp_player_intcelebrationfemale@air_shagging", "air_shagging", 8 },
            {"Секс-2", "anim@mp_player_intcelebrationfemale@dock", "dock", 8 },
            {"Курица", "anim@mp_player_intcelebrationfemale@chicken_taunt", "chicken_taunt", 8 },
            {"Дразнить-1", "anim@mp_player_intcelebrationfemale@jazz_hands", "jazz_hands", 8 },
            {"Дразнить-2", "anim@mp_player_intcelebrationfemale@thumb_on_ears", "thumb_on_ears", 8 },
            {"Дразнить-3", "anim@mp_player_intcelebrationmale@thumb_on_ears", "thumb_on_ears", 8 },
            {"Фотограф", "anim@mp_player_intcelebrationfemale@photography", "photography", 8 },
            {"Рок", "amb@code_human_in_car_mp_actions@rock@bodhi@rps@base", "idle_a", 8 },
            {"Гитарист", "anim@mp_player_intcelebrationfemale@air_guitar", "air_guitar", 8 },
            {"Труп", "anim@melee@machete@streamed_core@", "victim_front_takedown", 8 },
            {"Ломка", "creatures@rottweiler@melee@", "victim_takedown_from_front", 8 },
            {"Пробежка на месте", "amb@world_human_jog_standing@male@base", "base", 8 },
            {"Качаться", "anim@mp_player_intcelebrationmale@peace", "peace", 9 },
        };
    }
}